language: go
go_import_path: github.com/mresti/go_rest_api
go:
    - "1.10"
    - 1.9.x
    - 1.8.x
    - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
sudo: false
install:
    - go get -v github.com/alecthomas/gometalinter
    - gometalinter --install
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - test -z "$(gometalinter --disable-all
      --enable=gofmt
      --enable=golint
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --deadline=4m ./spew | tee /dev/stderr)"
    - make                 # Run format code, run tests and build code
    - make test # Run  tests
deploy:
  provider: script
  script: curl -X POST https://goreportcard.com/checks -F 'repo=github.com/mresti/go_rest_api'
  on:
    branch: master
